# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
   configuration: doc/recipes/docs/conf.py

formats:
   - epub
   - pdf

python:
   version: 3.7
   install:
   - requirements: doc/recipes/requirements.txt